class TimMember {
  final int id;
  final String imagePath;
  final String name;
  final String position;
  final int nip;
  final String nama;
  final String kodeDosen;
  final String email;
  final String status;
  final String prodi;
  final String fakultas;
  final String cabang;
  final int number;
  final String gender;
  final String agama;
  final String lahir;
  final DateTime date;
  final DateTime time;

  TimMember({
    required this.id,
    required this.imagePath,
    required this.name,
    required this.position,
    required this.nip,
    required this.nama,
    required this.kodeDosen,
    required this.email,
    required this.status,
    required this.prodi,
    required this.fakultas,
    required this.cabang,
    required this.number,
    required this.gender,
    required this.agama,
    required this.lahir,
    required this.date,  // Menambahkan dalam konstruktor
    required this.time,  // Menambahkan dalam konstruktor
  });
}
final List<TimMember> timMember = [
  TimMember(
    id: 1,
    imagePath: 'https://humic.telkomuniversity.ac.id/wp-content/uploads/2024/05/amilaa-1.png',
    name: 'Amila Nafila Vidyana, S.I.Kom',
    position: 'Staff',
    nip: 12345,
    nama: 'Amila Nafila Vidyana',
    kodeDosen: 'ANV',
    email: 'amila@telkomuniversity.ac.id',
    status: 'Aktif',
    prodi: 'Informatika',
    fakultas: 'Informatika',
    cabang: 'Bandung',
    gender: 'Perempuan',
    number: 0821234545,
    agama: 'Islam',
    lahir: '1997-03-14',
    date: DateTime(2024, 10, 19),
    time: DateTime(2024, 10, 19, 10, 30),
  ),
  TimMember(
    id: 2,
    imagePath: 'https://humic.telkomuniversity.ac.id/wp-content/uploads/2024/05/435A4423-1.jpg',
    name: 'Muhammad Rakha, S.T',
    position: 'Staff',
    nip: 12346,
    nama: 'Muhammad Rakha',
    kodeDosen: 'MRK',
    email: 'rakha@telkomuniversity.ac.id',
    status: 'Aktif',
    prodi: 'Teknik Informatika',
    fakultas: 'Fakultas Informatika',
    cabang: 'Bandung',
    gender: 'Pria',
    number: 0821234545,
    agama: 'Islam',
    lahir: '1997-03-14',
    date: DateTime(2024, 10, 19),
    time: DateTime(2024, 10, 19, 11, 15),
  ),
  TimMember(
    id: 3,
    imagePath: 'https://humic.telkomuniversity.ac.id/wp-content/uploads/2024/05/lastri-1.jpg',
    name: 'Lastrimurni Dongoran, S.Kom',
    position: 'Staff',
    nip: 12347,
    nama: 'Lastrimurni Dongoran',
    kodeDosen: 'LMD',
    email: 'lastri@telkomuniversity.ac.id',
    status: 'Aktif',
    prodi: 'Sistem Informasi',
    fakultas: 'Fakultas Rekayasa Industri',
    cabang: 'Bandung',
    gender: 'Perempuan',
    number: 0821234545,
    agama: 'Islam',
    lahir: '1997-03-14',
    date: DateTime(2024, 10, 19),
    time: DateTime(2024, 10, 19, 12, 0),
  ),
  TimMember(
    id: 4,
    imagePath: 'https://humic.telkomuniversity.ac.id/wp-content/uploads/2020/06/Adiwijaya.png',
    name: 'Prof. Dr. Adiwijaya, S.Si., M.Si.',
    position: 'Member',
    nip: 12348,
    nama: 'Adiwijaya',
    kodeDosen: 'ADW',
    email: 'adiwijaya@telkomuniversity.ac.id',
    status: 'Aktif',
    prodi: 'Informatika',
    fakultas: 'Fakultas Informatika',
    cabang: 'Bandung',
    gender: 'Pria',
    number: 0821234545,
    agama: 'Islam',
    lahir: '1997-03-14',
    date: DateTime(2024, 10, 19),
    time: DateTime(2024, 10, 19, 13, 45),
  ),
  TimMember(
    id: 5,
    imagePath: 'https://humic.telkomuniversity.ac.id/wp-content/uploads/2024/05/image-10-1.png',
    name: 'Prof. Dr. Tri Arief Sardjono, S.T., M.T.',
    position: 'Member',
    nip: 12349,
    nama: 'Tri Arief Sardjono',
    kodeDosen: 'TAS',
    email: 'sardjono@telkomuniversity.ac.id',
    status: 'Aktif',
    prodi: 'Teknik Elektro',
    fakultas: 'Fakultas Teknik Elektro',
    cabang: 'Bandung',
    gender: 'Pria',
    number: 0821234545,
    agama: 'Islam',
    lahir: '1997-03-14',
    date: DateTime(2024, 10, 19),
    time: DateTime(2024, 10, 19, 14, 30),
  ),
  TimMember(
    id: 6,
    imagePath: 'https://humic.telkomuniversity.ac.id/wp-content/uploads/2024/05/image-3.png',
    name: 'Dr. Tjokorda Agung Budi Wirayuda, S.T., M.T.',
    position: 'Member',
    nip: 12350,
    nama: 'Tjokorda Agung Budi Wirayuda',
    kodeDosen: 'TAB',
    email: 'tjokorda@telkomuniversity.ac.id',
    status: 'Aktif',
    prodi: 'Informatika',
    fakultas: 'Fakultas Informatika',
    cabang: 'Bandung',
    gender: 'Pria',
    number: 0821234545,
    agama: 'Islam',
    lahir: '1997-03-14',
    date: DateTime(2024, 10, 19),
    time: DateTime(2024, 10, 19, 15, 15),
  ),
  TimMember(
    id: 7,
    imagePath: 'https://humic.telkomuniversity.ac.id/wp-content/uploads/2024/05/image-4.png',
    name: 'Niken Dwi Wahyu Cahyani, S.T., M.Kom, Ph.D.',
    position: 'Member',
    nip: 12351,
    nama: 'Niken Dwi Wahyu Cahyani',
    kodeDosen: 'NDW',
    email: 'niken@telkomuniversity.ac.id',
    status: 'Aktif',
    prodi: 'Informatika',
    fakultas: 'Fakultas Informatika',
    cabang: 'Bandung',
    gender: 'Perempuan',
    number: 0821234545,
    agama: 'Islam',
    lahir: '1997-03-14',
    date: DateTime(2024, 10, 19),
    time: DateTime(2024, 10, 19, 16, 0),
  ),
  TimMember(
    id: 8,
    imagePath: 'https://humic.telkomuniversity.ac.id/wp-content/uploads/2024/05/image-5.png',
    name: 'Dandi Yunidar, S.Sn., M.Ds., Ph.D.',
    position: 'Member',
    nip: 12352,
    nama: 'Dandi Yunidar',
    kodeDosen: 'DYN',
    email: 'dandi@telkomuniversity.ac.id',
    status: 'Aktif',
    prodi: 'Desain Komunikasi Visual',
    fakultas: 'Fakultas Industri Kreatif',
    cabang: 'Bandung',
    gender: 'Pria',
    number: 0821234545,
    agama: 'Islam',
    lahir: '1997-03-14',
    date: DateTime(2024, 10, 19),
    time: DateTime(2024, 10, 19, 16, 45),
  ),
  TimMember(
    id: 9,
    imagePath: 'https://humic.telkomuniversity.ac.id/wp-content/uploads/2024/05/image-6-1.png',
    name: 'Dr. Ema Rachmawati, S.T., M.T.',
    position: 'Member',
    nip: 12353,
    nama: 'Ema Rachmawati',
    kodeDosen: 'EMR',
    email: 'ema@telkomuniversity.ac.id',
    status: 'Aktif',
    prodi: 'Teknik Industri',
    fakultas: 'Fakultas Rekayasa Industri',
    cabang: 'Bandung',
    gender: 'Perempuan',
    number: 0821234545,
    agama: 'Islam',
    lahir: '1997-03-14',
    date: DateTime(2024, 10, 19),
    time: DateTime(2024, 10, 19, 17, 30),
  ),
];
